# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.containerName }}-release
  namespace: {{ .Values.k8s.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.containerName }}
    spec:
      containers:
      - name: {{ .Values.image.containerName }}-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}         # Endpoint to check for readiness (adjust according to your app)
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: 20    # Wait 20 seconds before the first probe
          periodSeconds: 5         # Probe every 5 seconds
          timeoutSeconds: 2         # Timeout if the probe takes longer than 2 seconds
          failureThreshold: 3       # Mark the Pod as not ready after 3 consecutive failures        
