
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


ingress:
  certificateArn: ""
  securitygroup: ""
  subnets:
    subnetA: ""
    subnetB: ""
    subnetC: ""


routes:
  - path: /customer*
    serviceName: customer-service
    servicePort: 8080
    
  - path: /driver*
    serviceName: driver-service
    servicePort: 8080
